### PR TITLE
Added jumping to procedure begin from procedure call

### PR DESCRIPTION
**Pull request by prudowicz**
fixed jumping to line

### CODE REVIEW

**Comment by Jmgr** [comment]
Thanks for the PR! I'm a bit busy nowadays but I will have a look at it.

**Comment by Jmgr** [comment]
Apologies for not having reacted to this PR, I've been inactive on Actiona for a few years. Would you still be up to rebase this PR on main and update it?

**Comment by Jmgr** [comment]
Have you tried pulling the main branch and then rebasing on it? It seems that this PR has somehow got all the changes since an old commit.

**Comment by prudowicz** [comment]
Yes, I tried at it all looks too complicated. I think my best shot would be forking your repo again from your current branch and then add my changes and push PR again. Thank you for your answer, I will make a better description at what I want to add to your project and how I see it useful. This PR should be closed now.

**Comment by Jmgr** [comment]
Hm yes that's probably the simplest solution if you didn't have too many changes. Again, apologies for not having reacted sooner to your PR. It would have been easier to merge back then. Closing this for now.

**Pull request closed without merging**
